// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Notification struct {
	ID          int64     `json:"id"`
	Recipient   string    `json:"recipient"`
	Message     string    `json:"message"`
	ChannelType string    `json:"channel_type"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
